4.1/generic chart after file moves
oslabs-beta/Kubernautics pull request #10
Opened 2023-11-17 18:43 UTC by edli-dot

Same edits as before but I had to create a new branch to get rid of the .devspace.

Merged 3- Setup_react_frontend and 4/generic_chart in order to get a functional chart alongside frontend styling. The component framework has been laid out. Next steps would be to introduce additional state logic to manage all the charts on the ChartContainer.

An eventual goal would be to have the ability for the user to have some sort of chart-generating autonomy that would create these new instances of charts. Also need to implement the self-reloading of the charts. Time interval based on what kind of time duration the query is looking at.

2023-11-17 18:51 UTC, tylershelton commented
Hey @edli-dot, does this PR supercede PR #9 ? Or do both need to get merged into dev one after the other?

2023-11-17 18:58 UTC, edli-dot commented
There were still some additional merge conflicts w/ dev that probably resulted in having to do some command line merge. I just commit an additional change that has resolved this issue. So now at this current state of time, PR#9 has now been closed and the files within this PR should all be working

2023-11-17 19:46 UTC, tylershelton requested changes
Great! Just a couple small questions about whether a few commented-out sections need to be included for the future or not. Have a look.

2023-11-17 19:46 UTC, tylershelton commented on assets/styles.scss
> +// #monitor {
should we clean some of this commented-out CSS, or are we keeping it around for a reason?

2023-11-17 19:46 UTC, tylershelton commented on src/index.html
> +      <!-- <video autoplay muted loop id="myVideo">
Is this commented out video needed, or can we leave it out?

2023-11-17 20:12 UTC, edli-dot commented
You made a good insight with those uncommented codes. The ones in the index.html and styles.scss were just for testing and unneeded so I took them out. The uncommented code that might be useful later on for us to reference for handling chart state is now moved into MonitoringComponent.jsx.

2023-11-18 00:50 UTC, tylershelton approved these changes
Looking good!

2023-11-18 00:51 UTC, merged

2023-11-18 00:51 UTC, tylershelton commented
Merged into dev.